#! /usr/bin/env bash

function usage {
  echo "Usage: rhost [-q] fqdn"
  exit 1
}

while getopts q: option; do
  case "${option}" in
    q) QUIET=1;shift;;
    *) usage;;
  esac
done

# ta bort https osv
HOST1=${1/http*:\/\//}
HOST=${HOST1/\/*/}

ADDR=$(host $HOST|grep "has address")
if [ -z "$ADDR" ]; then
  exit;
fi

IFS=$'\n'
IFS=$'\n';
for ADDR in $(host $HOST|grep "has address"); do 
  if [ -z "${QUIET}" ]; then
    echo "IP: $ADDR"
  fi
  IP=$(echo "$ADDR" | sed -n 's/^.*has address //p')
  if [ -n "$IP" ]; then
    HOST=$(host "$IP")
    if [ -z "$QUIET" ]; then
      echo "Reverse: "$(echo $HOST|sed -n 's/^.*domain name pointer //p')
    else
      echo $(echo $HOST|sed -n 's/^.*domain name pointer //p')
    fi

    AS=$(whois "$IP" | grep -oh "AS[0-9]\+" | tail -1)
    if [ -n "$AS" ]; then
      echo "AS-num: $AS"
      ORG=$(whois "$AS" | grep -i -e OrgName -e org-name: | tr -s ' ')
      echo $ORG
    fi
  fi
  echo ""
done
exit


echo "---"
echo "$ADDR"
echo "^^^^"
